[package]
name = "apriltag-sys"
version = "0.1.2"
description = "Rust bindings for AprilTag library"
authors = ["jerry73204 <jerry73204@gmail.com>"]
edition = "2018"
license = "BSD-2-Clause"
documentation = "https://docs.rs/apriltag-sys"
homepage = "https://github.com/jerry73204/apriltag-sys"
repository = "https://github.com/jerry73204/apriltag-sys.git"
readme = "README.md"

[dependencies]

[build-dependencies]
bindgen = { version = "^0.53.1", optional = true }
cc = { version = "^1.0.50", features = ["parallel"], optional = true }
cmake = { version  = "^0.1.42", optional = true }
pkg-config = { version = "^0.3.17", optional = true }
lazy_static = "^1.4.0"

[features]
default = []
buildtime-bindgen = ["bindgen", "cc", "cmake", "pkg-config"]
